import type { Metadata } from 'next'
import { Comic_Neue, Azeret_Mono } from 'next/font/google'
import './globals.css'

const comic_Neue = Comic_Neue({
  weight: ['300', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-comic-neue'
})

const azeret_Mono = Azeret_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-azeret-mono'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${comic_Neue.variable} ${azeret_Mono.variable}`}>
      <body>{children}</body>
    </html>
  )
}
